version: "3.8"

networks:
  database-network:
    name: "database"

services:
  app:
    container_name: app
    build:
      dockerfile: docker/Dockerfile
      context: ..
      target: main
    environment:
      - "BUILD_TYPE=production"
    ports:
      - "8888:8888"
    networks:
      - database-network
  db:
    container_name: db
    hostname: db
    restart: unless-stopped
    image: postgres:14
    expose:
      - "5432"
    env_file:
      - "../.env"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
    networks:
      - database-network



volumes:
  db_data: {}
